package io.frame.dao.mapper;

import io.frame.dao.entity.GlobalRecord;
import io.frame.dao.entity.GlobalRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GlobalRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int countByExample(GlobalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int deleteByExample(GlobalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int insert(GlobalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int insertSelective(GlobalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    List<GlobalRecord> selectByExample(GlobalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    GlobalRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") GlobalRecord record, @Param("example") GlobalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") GlobalRecord record, @Param("example") GlobalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(GlobalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(GlobalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int insertBatch(List<GlobalRecord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int insertBatchSelective(@Param("showField") List<String> showField, @Param("list") List<GlobalRecord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    GlobalRecord selectOneByExample(GlobalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    GlobalRecord selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    List<GlobalRecord> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") GlobalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    GlobalRecord selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") GlobalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int updateByExampleSelectiveSync(@Param("record") GlobalRecord record, @Param("example") GlobalRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelectiveSync(GlobalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int upsert(GlobalRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_global_record
     *
     * @mbggenerated
     */
    int upsertSelective(GlobalRecord record);
}