package io.frame.dao.mapper;

import io.frame.dao.entity.Payment;
import io.frame.dao.entity.PaymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PaymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int countByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int deleteByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int insert(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int insertSelective(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    List<Payment> selectByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    Payment selectByPrimaryKey(Long paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Payment record, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Payment record, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int insertBatch(List<Payment> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int insertBatchSelective(@Param("showField") List<String> showField, @Param("list") List<Payment> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    Payment selectOneByExample(PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    Payment selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("paymentId") Long paymentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    List<Payment> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    Payment selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int updateByExampleSelectiveSync(@Param("record") Payment record, @Param("example") PaymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelectiveSync(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int upsert(Payment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_payment
     *
     * @mbggenerated
     */
    int upsertSelective(Payment record);
}