package io.frame.dao.mapper;

import io.frame.dao.entity.Recommend;
import io.frame.dao.entity.RecommendExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecommendMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int countByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int deleteByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long recommendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int insert(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int insertSelective(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    List<Recommend> selectByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    Recommend selectByPrimaryKey(Long recommendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Recommend record, @Param("example") RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Recommend record, @Param("example") RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int insertBatch(List<Recommend> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int insertBatchSelective(@Param("showField") List<String> showField, @Param("list") List<Recommend> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    Recommend selectOneByExample(RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    Recommend selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("recommendId") Long recommendId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    List<Recommend> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    Recommend selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int updateByExampleSelectiveSync(@Param("record") Recommend record, @Param("example") RecommendExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelectiveSync(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int upsert(Recommend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    int upsertSelective(Recommend record);
}