package io.frame.dao.mapper;

import io.frame.dao.entity.ScheduleJobLog;
import io.frame.dao.entity.ScheduleJobLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScheduleJobLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int countByExample(ScheduleJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int deleteByExample(ScheduleJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int insert(ScheduleJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int insertSelective(ScheduleJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    List<ScheduleJobLog> selectByExample(ScheduleJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    ScheduleJobLog selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ScheduleJobLog record, @Param("example") ScheduleJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ScheduleJobLog record, @Param("example") ScheduleJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ScheduleJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ScheduleJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int insertBatch(List<ScheduleJobLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int insertBatchSelective(@Param("showField") List<String> showField, @Param("list") List<ScheduleJobLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    ScheduleJobLog selectOneByExample(ScheduleJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    ScheduleJobLog selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("logId") Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    List<ScheduleJobLog> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") ScheduleJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    ScheduleJobLog selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") ScheduleJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int updateByExampleSelectiveSync(@Param("record") ScheduleJobLog record, @Param("example") ScheduleJobLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelectiveSync(ScheduleJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int upsert(ScheduleJobLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job_log
     *
     * @mbggenerated
     */
    int upsertSelective(ScheduleJobLog record);
}