package io.frame.dao.mapper;

import io.frame.dao.entity.ScheduleJob;
import io.frame.dao.entity.ScheduleJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ScheduleJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int countByExample(ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int deleteByExample(ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int insert(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int insertSelective(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    List<ScheduleJob> selectByExample(ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    ScheduleJob selectByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ScheduleJob record, @Param("example") ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ScheduleJob record, @Param("example") ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int insertBatch(List<ScheduleJob> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int insertBatchSelective(@Param("showField") List<String> showField, @Param("list") List<ScheduleJob> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    ScheduleJob selectOneByExample(ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    ScheduleJob selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("jobId") Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    List<ScheduleJob> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    ScheduleJob selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int updateByExampleSelectiveSync(@Param("record") ScheduleJob record, @Param("example") ScheduleJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelectiveSync(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int upsert(ScheduleJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_schedule_job
     *
     * @mbggenerated
     */
    int upsertSelective(ScheduleJob record);
}