package io.frame.dao.mapper;

import io.frame.dao.entity.SpecialRecord;
import io.frame.dao.entity.SpecialRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpecialRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int countByExample(SpecialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int deleteByExample(SpecialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int insert(SpecialRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int insertSelective(SpecialRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    List<SpecialRecord> selectByExample(SpecialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    SpecialRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SpecialRecord record, @Param("example") SpecialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SpecialRecord record, @Param("example") SpecialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SpecialRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SpecialRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int insertBatch(List<SpecialRecord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int insertBatchSelective(@Param("showField") List<String> showField, @Param("list") List<SpecialRecord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    SpecialRecord selectOneByExample(SpecialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    SpecialRecord selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    List<SpecialRecord> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") SpecialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    SpecialRecord selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") SpecialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int updateByExampleSelectiveSync(@Param("record") SpecialRecord record, @Param("example") SpecialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelectiveSync(SpecialRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int upsert(SpecialRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_special_record
     *
     * @mbggenerated
     */
    int upsertSelective(SpecialRecord record);
}