package io.frame.dao.mapper;

import io.frame.dao.entity.SysRoleDept;
import io.frame.dao.entity.SysRoleDeptExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysRoleDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int countByExample(SysRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int deleteByExample(SysRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int insert(SysRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int insertSelective(SysRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    List<SysRoleDept> selectByExample(SysRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    SysRoleDept selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SysRoleDept record, @Param("example") SysRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SysRoleDept record, @Param("example") SysRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SysRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int insertBatch(List<SysRoleDept> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int insertBatchSelective(@Param("showField") List<String> showField, @Param("list") List<SysRoleDept> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    SysRoleDept selectOneByExample(SysRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    SysRoleDept selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    List<SysRoleDept> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") SysRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    SysRoleDept selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") SysRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int updateByExampleSelectiveSync(@Param("record") SysRoleDept record, @Param("example") SysRoleDeptExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelectiveSync(SysRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int upsert(SysRoleDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_dept
     *
     * @mbggenerated
     */
    int upsertSelective(SysRoleDept record);
}