package io.frame.dao.mapper;

import io.frame.dao.entity.TeamleaderRecord;
import io.frame.dao.entity.TeamleaderRecordExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamleaderRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int countByExample(TeamleaderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int deleteByExample(TeamleaderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int insert(TeamleaderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int insertSelective(TeamleaderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    List<TeamleaderRecord> selectByExample(TeamleaderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    TeamleaderRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TeamleaderRecord record, @Param("example") TeamleaderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TeamleaderRecord record, @Param("example") TeamleaderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TeamleaderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TeamleaderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int insertBatch(List<TeamleaderRecord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int insertBatchSelective(@Param("showField") List<String> showField, @Param("list") List<TeamleaderRecord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    TeamleaderRecord selectOneByExample(TeamleaderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    TeamleaderRecord selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("id") Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    List<TeamleaderRecord> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") TeamleaderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    TeamleaderRecord selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") TeamleaderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int updateByExampleSelectiveSync(@Param("record") TeamleaderRecord record, @Param("example") TeamleaderRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelectiveSync(TeamleaderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int upsert(TeamleaderRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_teamleader_record
     *
     * @mbggenerated
     */
    int upsertSelective(TeamleaderRecord record);
}