package io.frame.dao.mapper;

import io.frame.dao.entity.Token;
import io.frame.dao.entity.TokenExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TokenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int countByExample(TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int deleteByExample(TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int insert(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int insertSelective(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    List<Token> selectByExample(TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    Token selectByPrimaryKey(Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Token record, @Param("example") TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Token record, @Param("example") TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int insertBatch(List<Token> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int insertBatchSelective(@Param("showField") List<String> showField, @Param("list") List<Token> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    Token selectOneByExample(TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    Token selectByPrimaryKeyShowField(@Param("showField") List<String> showField, @Param("userId") Long userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    List<Token> selectByExampleShowField(@Param("showField") List<String> showField, @Param("example") TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    Token selectOneByExampleShowField(@Param("showField") List<String> showField, @Param("example") TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int updateByExampleSelectiveSync(@Param("record") Token record, @Param("example") TokenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelectiveSync(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int upsert(Token record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    int upsertSelective(Token record);
}