spring:
    ##json格式化
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8
    # 环境 dev|test|prod
    profiles:
        active: dev
    servlet:
      multipart:
        enabled: true
        max-file-size: 20MB
        max-request-size: 20MB
    freemarker:
      suffix: .html
      request-context-attribute: request

frame:
    redis:
        open: false  # 是否开启redis缓存  true开启   false关闭
    shiro:
        redis: false # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】

#mybatis
mybatis:
  mapper-locations: classpath*:io/frame/dao/mapper/*.xml,io/frame/dao/custom/mapper/*.xml
  type-aliases-package: io.frame.dao.entity   #实体扫描，多个package用逗号或者分号分隔
#分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql 

logging:
  level: debug
  level.io.frame: debug
  path: logs/
  file: admin.log