package io.frame.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_config
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_config
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_config
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public ConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_config
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public void setOrderByClauseIgnoreNull(String orderByClause) {
        String tmp = orderByClause.toLowerCase().replace("null", "").replace("asc", "").replace("desc", "").trim();
        if (orderByClause != null && tmp.length() > 0) {
            this.orderByClause = orderByClause;}
        }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_config
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andConfigIdIsNull() {
            addCriterion("configId is null");
            return (Criteria) this;
        }

        public Criteria andConfigIdIsNotNull() {
            addCriterion("configId is not null");
            return (Criteria) this;
        }

        public Criteria andConfigIdEqualTo(Long value) {
            addCriterion("configId =", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotEqualTo(Long value) {
            addCriterion("configId <>", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdGreaterThan(Long value) {
            addCriterion("configId >", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdGreaterThanOrEqualTo(Long value) {
            addCriterion("configId >=", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdLessThan(Long value) {
            addCriterion("configId <", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdLessThanOrEqualTo(Long value) {
            addCriterion("configId <=", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdIn(List<Long> values) {
            addCriterion("configId in", values, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotIn(List<Long> values) {
            addCriterion("configId not in", values, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdBetween(Long value1, Long value2) {
            addCriterion("configId between", value1, value2, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotBetween(Long value1, Long value2) {
            addCriterion("configId not between", value1, value2, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigKeyIsNull() {
            addCriterion("configKey is null");
            return (Criteria) this;
        }

        public Criteria andConfigKeyIsNotNull() {
            addCriterion("configKey is not null");
            return (Criteria) this;
        }

        public Criteria andConfigKeyEqualTo(String value) {
            addCriterion("configKey =", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyNotEqualTo(String value) {
            addCriterion("configKey <>", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyGreaterThan(String value) {
            addCriterion("configKey >", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyGreaterThanOrEqualTo(String value) {
            addCriterion("configKey >=", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyLessThan(String value) {
            addCriterion("configKey <", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyLessThanOrEqualTo(String value) {
            addCriterion("configKey <=", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyLike(String value) {
            addCriterion("configKey like", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyNotLike(String value) {
            addCriterion("configKey not like", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyIn(List<String> values) {
            addCriterion("configKey in", values, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyNotIn(List<String> values) {
            addCriterion("configKey not in", values, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyBetween(String value1, String value2) {
            addCriterion("configKey between", value1, value2, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyNotBetween(String value1, String value2) {
            addCriterion("configKey not between", value1, value2, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigValIsNull() {
            addCriterion("configVal is null");
            return (Criteria) this;
        }

        public Criteria andConfigValIsNotNull() {
            addCriterion("configVal is not null");
            return (Criteria) this;
        }

        public Criteria andConfigValEqualTo(String value) {
            addCriterion("configVal =", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValNotEqualTo(String value) {
            addCriterion("configVal <>", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValGreaterThan(String value) {
            addCriterion("configVal >", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValGreaterThanOrEqualTo(String value) {
            addCriterion("configVal >=", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValLessThan(String value) {
            addCriterion("configVal <", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValLessThanOrEqualTo(String value) {
            addCriterion("configVal <=", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValLike(String value) {
            addCriterion("configVal like", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValNotLike(String value) {
            addCriterion("configVal not like", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValIn(List<String> values) {
            addCriterion("configVal in", values, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValNotIn(List<String> values) {
            addCriterion("configVal not in", values, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValBetween(String value1, String value2) {
            addCriterion("configVal between", value1, value2, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValNotBetween(String value1, String value2) {
            addCriterion("configVal not between", value1, value2, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigNameIsNull() {
            addCriterion("configName is null");
            return (Criteria) this;
        }

        public Criteria andConfigNameIsNotNull() {
            addCriterion("configName is not null");
            return (Criteria) this;
        }

        public Criteria andConfigNameEqualTo(String value) {
            addCriterion("configName =", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameNotEqualTo(String value) {
            addCriterion("configName <>", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameGreaterThan(String value) {
            addCriterion("configName >", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameGreaterThanOrEqualTo(String value) {
            addCriterion("configName >=", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameLessThan(String value) {
            addCriterion("configName <", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameLessThanOrEqualTo(String value) {
            addCriterion("configName <=", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameLike(String value) {
            addCriterion("configName like", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameNotLike(String value) {
            addCriterion("configName not like", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameIn(List<String> values) {
            addCriterion("configName in", values, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameNotIn(List<String> values) {
            addCriterion("configName not in", values, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameBetween(String value1, String value2) {
            addCriterion("configName between", value1, value2, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameNotBetween(String value1, String value2) {
            addCriterion("configName not between", value1, value2, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigTypeIsNull() {
            addCriterion("configType is null");
            return (Criteria) this;
        }

        public Criteria andConfigTypeIsNotNull() {
            addCriterion("configType is not null");
            return (Criteria) this;
        }

        public Criteria andConfigTypeEqualTo(String value) {
            addCriterion("configType =", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeNotEqualTo(String value) {
            addCriterion("configType <>", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeGreaterThan(String value) {
            addCriterion("configType >", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeGreaterThanOrEqualTo(String value) {
            addCriterion("configType >=", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeLessThan(String value) {
            addCriterion("configType <", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeLessThanOrEqualTo(String value) {
            addCriterion("configType <=", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeLike(String value) {
            addCriterion("configType like", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeNotLike(String value) {
            addCriterion("configType not like", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeIn(List<String> values) {
            addCriterion("configType in", values, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeNotIn(List<String> values) {
            addCriterion("configType not in", values, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeBetween(String value1, String value2) {
            addCriterion("configType between", value1, value2, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeNotBetween(String value1, String value2) {
            addCriterion("configType not between", value1, value2, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigStatusIsNull() {
            addCriterion("configStatus is null");
            return (Criteria) this;
        }

        public Criteria andConfigStatusIsNotNull() {
            addCriterion("configStatus is not null");
            return (Criteria) this;
        }

        public Criteria andConfigStatusEqualTo(Integer value) {
            addCriterion("configStatus =", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusNotEqualTo(Integer value) {
            addCriterion("configStatus <>", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusGreaterThan(Integer value) {
            addCriterion("configStatus >", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("configStatus >=", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusLessThan(Integer value) {
            addCriterion("configStatus <", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusLessThanOrEqualTo(Integer value) {
            addCriterion("configStatus <=", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusIn(List<Integer> values) {
            addCriterion("configStatus in", values, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusNotIn(List<Integer> values) {
            addCriterion("configStatus not in", values, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusBetween(Integer value1, Integer value2) {
            addCriterion("configStatus between", value1, value2, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("configStatus not between", value1, value2, "configStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("createUser is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("createUser is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("createUser =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("createUser <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("createUser >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("createUser >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("createUser <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("createUser <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("createUser like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("createUser not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("createUser in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("createUser not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("createUser between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("createUser not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("updateUser is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("updateUser is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("updateUser =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("updateUser <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("updateUser >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("updateUser >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("updateUser <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("updateUser <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("updateUser like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("updateUser not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("updateUser in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("updateUser not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("updateUser between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("updateUser not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andConfigKeyLikeInsensitive(String value) {
            addCriterion("upper(configKey) like", value.toUpperCase(), "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigValLikeInsensitive(String value) {
            addCriterion("upper(configVal) like", value.toUpperCase(), "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigNameLikeInsensitive(String value) {
            addCriterion("upper(configName) like", value.toUpperCase(), "configName");
            return (Criteria) this;
        }

        public Criteria andConfigTypeLikeInsensitive(String value) {
            addCriterion("upper(configType) like", value.toUpperCase(), "configType");
            return (Criteria) this;
        }

        public Criteria andCreateUserLikeInsensitive(String value) {
            addCriterion("upper(createUser) like", value.toUpperCase(), "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLikeInsensitive(String value) {
            addCriterion("upper(updateUser) like", value.toUpperCase(), "updateUser");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }

        protected void addCriterionIgnoreNull(String condition, Object value, String property) {
            if (value != null) {
                if (value instanceof String) {
                    if (condition.toLowerCase().endsWith("like")) {
                        if (((String) value).replaceAll("%", "").length() > 0) {
                            criteria.add(new Criterion(condition, value));
                        }
                    } else if (((String) value).length() > 0) {
                        criteria.add(new Criterion(condition, value));
                    }
                } else if (value instanceof List<?>) {
                    if (((List<?>) value).size() > 0) {
                        criteria.add(new Criterion(condition, value));
                    }
                } else {
                    criteria.add(new Criterion(condition, value));
                }
            }
        }

        public Criteria andConfigIdEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("configId =", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("configId <>", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdGreaterThanIgnoreNull(Long value) {
            addCriterionIgnoreNull("configId >", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdGreaterThanOrEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("configId >=", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdLessThanIgnoreNull(Long value) {
            addCriterionIgnoreNull("configId <", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdLessThanOrEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("configId <=", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdInIgnoreNull(List<Long> value) {
            addCriterionIgnoreNull("configId in", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigIdNotInIgnoreNull(List<Long> value) {
            addCriterionIgnoreNull("configId not in", value, "configId");
            return (Criteria) this;
        }

        public Criteria andConfigKeyEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configKey =", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configKey <>", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("configKey >", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configKey >=", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("configKey <", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configKey <=", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("configKey like", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("configKey not like", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("configKey in", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigKeyNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("configKey not in", value, "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigValEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configVal =", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configVal <>", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("configVal >", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configVal >=", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("configVal <", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configVal <=", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("configVal like", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("configVal not like", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("configVal in", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigValNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("configVal not in", value, "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigNameEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configName =", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configName <>", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("configName >", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configName >=", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("configName <", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configName <=", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("configName like", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("configName not like", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("configName in", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigNameNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("configName not in", value, "configName");
            return (Criteria) this;
        }

        public Criteria andConfigTypeEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configType =", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configType <>", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("configType >", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configType >=", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("configType <", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("configType <=", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("configType like", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("configType not like", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("configType in", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigTypeNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("configType not in", value, "configType");
            return (Criteria) this;
        }

        public Criteria andConfigStatusEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("configStatus =", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusNotEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("configStatus <>", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusGreaterThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("configStatus >", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusGreaterThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("configStatus >=", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusLessThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("configStatus <", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusLessThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("configStatus <=", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("configStatus in", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andConfigStatusNotInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("configStatus not in", value, "configStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("createTime in", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("createTime not in", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("createUser in", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("createUser not in", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("updateTime =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("updateTime <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("updateTime >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("updateTime >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("updateTime <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("updateTime <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("updateTime in", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("updateTime not in", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("updateUser in", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("updateUser not in", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("remark in", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("remark not in", value, "remark");
            return (Criteria) this;
        }

        public Criteria andConfigKeyLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(configKey) like", value.toUpperCase(), "configKey");
            return (Criteria) this;
        }

        public Criteria andConfigValLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(configVal) like", value.toUpperCase(), "configVal");
            return (Criteria) this;
        }

        public Criteria andConfigNameLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(configName) like", value.toUpperCase(), "configName");
            return (Criteria) this;
        }

        public Criteria andConfigTypeLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(configType) like", value.toUpperCase(), "configType");
            return (Criteria) this;
        }

        public Criteria andCreateUserLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(createUser) like", value.toUpperCase(), "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(updateUser) like", value.toUpperCase(), "updateUser");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andConfigIdLikeInsensitive(String value) {
            addCriterion("upper(configId) like", value.toUpperCase(), "configId");
            return this;
        }

        public Criteria andConfigKeyLikeInsensitive(String value) {
            addCriterion("upper(configKey) like", value.toUpperCase(), "configKey");
            return this;
        }

        public Criteria andConfigValLikeInsensitive(String value) {
            addCriterion("upper(configVal) like", value.toUpperCase(), "configVal");
            return this;
        }

        public Criteria andConfigNameLikeInsensitive(String value) {
            addCriterion("upper(configName) like", value.toUpperCase(), "configName");
            return this;
        }

        public Criteria andConfigTypeLikeInsensitive(String value) {
            addCriterion("upper(configType) like", value.toUpperCase(), "configType");
            return this;
        }

        public Criteria andConfigStatusLikeInsensitive(String value) {
            addCriterion("upper(configStatus) like", value.toUpperCase(), "configStatus");
            return this;
        }

        public Criteria andCreateTimeLikeInsensitive(String value) {
            addCriterion("upper(createTime) like", value.toUpperCase(), "createTime");
            return this;
        }

        public Criteria andCreateUserLikeInsensitive(String value) {
            addCriterion("upper(createUser) like", value.toUpperCase(), "createUser");
            return this;
        }

        public Criteria andUpdateTimeLikeInsensitive(String value) {
            addCriterion("upper(updateTime) like", value.toUpperCase(), "updateTime");
            return this;
        }

        public Criteria andUpdateUserLikeInsensitive(String value) {
            addCriterion("upper(updateUser) like", value.toUpperCase(), "updateUser");
            return this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_config
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}