package io.frame.dao.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class LogExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_log
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_log
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_log
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public LogExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public void setOrderByClauseIgnoreNull(String orderByClause) {
        String tmp = orderByClause.toLowerCase().replace("null", "").replace("asc", "").replace("desc", "").trim();
        if (orderByClause != null && tmp.length() > 0) {
            this.orderByClause = orderByClause;}
        }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_log
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andLogIdIsNull() {
            addCriterion("logId is null");
            return (Criteria) this;
        }

        public Criteria andLogIdIsNotNull() {
            addCriterion("logId is not null");
            return (Criteria) this;
        }

        public Criteria andLogIdEqualTo(Long value) {
            addCriterion("logId =", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotEqualTo(Long value) {
            addCriterion("logId <>", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThan(Long value) {
            addCriterion("logId >", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThanOrEqualTo(Long value) {
            addCriterion("logId >=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThan(Long value) {
            addCriterion("logId <", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThanOrEqualTo(Long value) {
            addCriterion("logId <=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdIn(List<Long> values) {
            addCriterion("logId in", values, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotIn(List<Long> values) {
            addCriterion("logId not in", values, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdBetween(Long value1, Long value2) {
            addCriterion("logId between", value1, value2, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotBetween(Long value1, Long value2) {
            addCriterion("logId not between", value1, value2, "logId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("userName is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("userName is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("userName =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("userName <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("userName >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("userName >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("userName <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("userName <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("userName like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("userName not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("userName in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("userName not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("userName between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("userName not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andOperationIsNull() {
            addCriterion("operation is null");
            return (Criteria) this;
        }

        public Criteria andOperationIsNotNull() {
            addCriterion("operation is not null");
            return (Criteria) this;
        }

        public Criteria andOperationEqualTo(String value) {
            addCriterion("operation =", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotEqualTo(String value) {
            addCriterion("operation <>", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationGreaterThan(String value) {
            addCriterion("operation >", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationGreaterThanOrEqualTo(String value) {
            addCriterion("operation >=", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationLessThan(String value) {
            addCriterion("operation <", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationLessThanOrEqualTo(String value) {
            addCriterion("operation <=", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationLike(String value) {
            addCriterion("operation like", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotLike(String value) {
            addCriterion("operation not like", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationIn(List<String> values) {
            addCriterion("operation in", values, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotIn(List<String> values) {
            addCriterion("operation not in", values, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationBetween(String value1, String value2) {
            addCriterion("operation between", value1, value2, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotBetween(String value1, String value2) {
            addCriterion("operation not between", value1, value2, "operation");
            return (Criteria) this;
        }

        public Criteria andMethodIsNull() {
            addCriterion("method is null");
            return (Criteria) this;
        }

        public Criteria andMethodIsNotNull() {
            addCriterion("method is not null");
            return (Criteria) this;
        }

        public Criteria andMethodEqualTo(String value) {
            addCriterion("method =", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotEqualTo(String value) {
            addCriterion("method <>", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThan(String value) {
            addCriterion("method >", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThanOrEqualTo(String value) {
            addCriterion("method >=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThan(String value) {
            addCriterion("method <", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThanOrEqualTo(String value) {
            addCriterion("method <=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLike(String value) {
            addCriterion("method like", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotLike(String value) {
            addCriterion("method not like", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodIn(List<String> values) {
            addCriterion("method in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotIn(List<String> values) {
            addCriterion("method not in", values, "method");
            return (Criteria) this;
        }

        public Criteria andMethodBetween(String value1, String value2) {
            addCriterion("method between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotBetween(String value1, String value2) {
            addCriterion("method not between", value1, value2, "method");
            return (Criteria) this;
        }

        public Criteria andParamsIsNull() {
            addCriterion("params is null");
            return (Criteria) this;
        }

        public Criteria andParamsIsNotNull() {
            addCriterion("params is not null");
            return (Criteria) this;
        }

        public Criteria andParamsEqualTo(String value) {
            addCriterion("params =", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsNotEqualTo(String value) {
            addCriterion("params <>", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsGreaterThan(String value) {
            addCriterion("params >", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsGreaterThanOrEqualTo(String value) {
            addCriterion("params >=", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsLessThan(String value) {
            addCriterion("params <", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsLessThanOrEqualTo(String value) {
            addCriterion("params <=", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsLike(String value) {
            addCriterion("params like", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsNotLike(String value) {
            addCriterion("params not like", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsIn(List<String> values) {
            addCriterion("params in", values, "params");
            return (Criteria) this;
        }

        public Criteria andParamsNotIn(List<String> values) {
            addCriterion("params not in", values, "params");
            return (Criteria) this;
        }

        public Criteria andParamsBetween(String value1, String value2) {
            addCriterion("params between", value1, value2, "params");
            return (Criteria) this;
        }

        public Criteria andParamsNotBetween(String value1, String value2) {
            addCriterion("params not between", value1, value2, "params");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Long value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Long value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Long value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Long value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Long value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Long value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Long> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Long> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Long value1, Long value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Long value1, Long value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("ip is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("ip is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("ip in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("ip not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("ip between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("ip not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andSourcesIsNull() {
            addCriterion("sources is null");
            return (Criteria) this;
        }

        public Criteria andSourcesIsNotNull() {
            addCriterion("sources is not null");
            return (Criteria) this;
        }

        public Criteria andSourcesEqualTo(Integer value) {
            addCriterion("sources =", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesNotEqualTo(Integer value) {
            addCriterion("sources <>", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesGreaterThan(Integer value) {
            addCriterion("sources >", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesGreaterThanOrEqualTo(Integer value) {
            addCriterion("sources >=", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesLessThan(Integer value) {
            addCriterion("sources <", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesLessThanOrEqualTo(Integer value) {
            addCriterion("sources <=", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesIn(List<Integer> values) {
            addCriterion("sources in", values, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesNotIn(List<Integer> values) {
            addCriterion("sources not in", values, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesBetween(Integer value1, Integer value2) {
            addCriterion("sources between", value1, value2, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesNotBetween(Integer value1, Integer value2) {
            addCriterion("sources not between", value1, value2, "sources");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUserNameLikeInsensitive(String value) {
            addCriterion("upper(userName) like", value.toUpperCase(), "userName");
            return (Criteria) this;
        }

        public Criteria andOperationLikeInsensitive(String value) {
            addCriterion("upper(operation) like", value.toUpperCase(), "operation");
            return (Criteria) this;
        }

        public Criteria andMethodLikeInsensitive(String value) {
            addCriterion("upper(method) like", value.toUpperCase(), "method");
            return (Criteria) this;
        }

        public Criteria andParamsLikeInsensitive(String value) {
            addCriterion("upper(params) like", value.toUpperCase(), "params");
            return (Criteria) this;
        }

        public Criteria andIpLikeInsensitive(String value) {
            addCriterion("upper(ip) like", value.toUpperCase(), "ip");
            return (Criteria) this;
        }

        protected void addCriterionIgnoreNull(String condition, Object value, String property) {
            if (value != null) {
                if (value instanceof String) {
                    if (condition.toLowerCase().endsWith("like")) {
                        if (((String) value).replaceAll("%", "").length() > 0) {
                            criteria.add(new Criterion(condition, value));
                        }
                    } else if (((String) value).length() > 0) {
                        criteria.add(new Criterion(condition, value));
                    }
                } else if (value instanceof List<?>) {
                    if (((List<?>) value).size() > 0) {
                        criteria.add(new Criterion(condition, value));
                    }
                } else {
                    criteria.add(new Criterion(condition, value));
                }
            }
        }

        public Criteria andLogIdEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("logId =", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("logId <>", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThanIgnoreNull(Long value) {
            addCriterionIgnoreNull("logId >", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdGreaterThanOrEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("logId >=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThanIgnoreNull(Long value) {
            addCriterionIgnoreNull("logId <", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdLessThanOrEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("logId <=", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdInIgnoreNull(List<Long> value) {
            addCriterionIgnoreNull("logId in", value, "logId");
            return (Criteria) this;
        }

        public Criteria andLogIdNotInIgnoreNull(List<Long> value) {
            addCriterionIgnoreNull("logId not in", value, "logId");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("userName =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("userName <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("userName >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("userName >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("userName <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("userName <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("userName like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("userName not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("userName in", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("userName not in", value, "userName");
            return (Criteria) this;
        }

        public Criteria andOperationEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("operation =", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("operation <>", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("operation >", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("operation >=", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("operation <", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("operation <=", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("operation like", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("operation not like", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("operation in", value, "operation");
            return (Criteria) this;
        }

        public Criteria andOperationNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("operation not in", value, "operation");
            return (Criteria) this;
        }

        public Criteria andMethodEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("method =", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("method <>", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("method >", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("method >=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("method <", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("method <=", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("method like", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("method not like", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("method in", value, "method");
            return (Criteria) this;
        }

        public Criteria andMethodNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("method not in", value, "method");
            return (Criteria) this;
        }

        public Criteria andParamsEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("params =", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("params <>", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("params >", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("params >=", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("params <", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("params <=", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("params like", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("params not like", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("params in", value, "params");
            return (Criteria) this;
        }

        public Criteria andParamsNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("params not in", value, "params");
            return (Criteria) this;
        }

        public Criteria andTimeEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanIgnoreNull(Long value) {
            addCriterionIgnoreNull("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanIgnoreNull(Long value) {
            addCriterionIgnoreNull("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeInIgnoreNull(List<Long> value) {
            addCriterionIgnoreNull("time in", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotInIgnoreNull(List<Long> value) {
            addCriterionIgnoreNull("time not in", value, "time");
            return (Criteria) this;
        }

        public Criteria andIpEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("ip =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("ip <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("ip >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("ip >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("ip <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("ip <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("ip like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("ip not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("ip in", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("ip not in", value, "ip");
            return (Criteria) this;
        }

        public Criteria andSourcesEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("sources =", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesNotEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("sources <>", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesGreaterThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("sources >", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesGreaterThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("sources >=", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesLessThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("sources <", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesLessThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("sources <=", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("sources in", value, "sources");
            return (Criteria) this;
        }

        public Criteria andSourcesNotInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("sources not in", value, "sources");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("createTime in", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("createTime not in", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andUserNameLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(userName) like", value.toUpperCase(), "userName");
            return (Criteria) this;
        }

        public Criteria andOperationLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(operation) like", value.toUpperCase(), "operation");
            return (Criteria) this;
        }

        public Criteria andMethodLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(method) like", value.toUpperCase(), "method");
            return (Criteria) this;
        }

        public Criteria andParamsLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(params) like", value.toUpperCase(), "params");
            return (Criteria) this;
        }

        public Criteria andIpLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(ip) like", value.toUpperCase(), "ip");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andLogIdLikeInsensitive(String value) {
            addCriterion("upper(logId) like", value.toUpperCase(), "logId");
            return this;
        }

        public Criteria andUserNameLikeInsensitive(String value) {
            addCriterion("upper(userName) like", value.toUpperCase(), "userName");
            return this;
        }

        public Criteria andOperationLikeInsensitive(String value) {
            addCriterion("upper(operation) like", value.toUpperCase(), "operation");
            return this;
        }

        public Criteria andMethodLikeInsensitive(String value) {
            addCriterion("upper(method) like", value.toUpperCase(), "method");
            return this;
        }

        public Criteria andParamsLikeInsensitive(String value) {
            addCriterion("upper(params) like", value.toUpperCase(), "params");
            return this;
        }

        public Criteria andTimeLikeInsensitive(String value) {
            addCriterion("upper(time) like", value.toUpperCase(), "time");
            return this;
        }

        public Criteria andIpLikeInsensitive(String value) {
            addCriterion("upper(ip) like", value.toUpperCase(), "ip");
            return this;
        }

        public Criteria andSourcesLikeInsensitive(String value) {
            addCriterion("upper(sources) like", value.toUpperCase(), "sources");
            return this;
        }

        public Criteria andCreateTimeLikeInsensitive(String value) {
            addCriterion("upper(createTime) like", value.toUpperCase(), "createTime");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s_log
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}