package io.frame.dao.entity;

import io.frame.dao.base.BaseEntity;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Product extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.productId
     *
     * @mbggenerated
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.productName
     *
     * @mbggenerated
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.productTypeId
     *
     * @mbggenerated
     */
    private Integer productTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.saleMoney
     *
     * @mbggenerated
     */
    private BigDecimal saleMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.saleQuantity
     *
     * @mbggenerated
     */
    private Integer saleQuantity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.saleVolumes
     *
     * @mbggenerated
     */
    private Integer saleVolumes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.rebateMoney
     *
     * @mbggenerated
     */
    private BigDecimal rebateMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.rebatePeriods
     *
     * @mbggenerated
     */
    private Integer rebatePeriods;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.rebateTotals
     *
     * @mbggenerated
     */
    private BigDecimal rebateTotals;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.purchaseRestriction
     *
     * @mbggenerated
     */
    private Integer purchaseRestriction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.startRebateTime
     *
     * @mbggenerated
     */
    private Integer startRebateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.productImgurl
     *
     * @mbggenerated
     */
    private String productImgurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.sort
     *
     * @mbggenerated
     */
    private Integer sort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.createUser
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.updateUser
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_product
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.productId
     *
     * @mbggenerated
     */
    public static final String FD_PRODUCTID = "productId";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.productName
     *
     * @mbggenerated
     */
    public static final String FD_PRODUCTNAME = "productName";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.productTypeId
     *
     * @mbggenerated
     */
    public static final String FD_PRODUCTTYPEID = "productTypeId";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.saleMoney
     *
     * @mbggenerated
     */
    public static final String FD_SALEMONEY = "saleMoney";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.saleQuantity
     *
     * @mbggenerated
     */
    public static final String FD_SALEQUANTITY = "saleQuantity";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.saleVolumes
     *
     * @mbggenerated
     */
    public static final String FD_SALEVOLUMES = "saleVolumes";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.rebateMoney
     *
     * @mbggenerated
     */
    public static final String FD_REBATEMONEY = "rebateMoney";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.rebatePeriods
     *
     * @mbggenerated
     */
    public static final String FD_REBATEPERIODS = "rebatePeriods";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.rebateTotals
     *
     * @mbggenerated
     */
    public static final String FD_REBATETOTALS = "rebateTotals";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.purchaseRestriction
     *
     * @mbggenerated
     */
    public static final String FD_PURCHASERESTRICTION = "purchaseRestriction";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.startRebateTime
     *
     * @mbggenerated
     */
    public static final String FD_STARTREBATETIME = "startRebateTime";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.status
     *
     * @mbggenerated
     */
    public static final String FD_STATUS = "status";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.productImgurl
     *
     * @mbggenerated
     */
    public static final String FD_PRODUCTIMGURL = "productImgurl";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.sort
     *
     * @mbggenerated
     */
    public static final String FD_SORT = "sort";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.remark
     *
     * @mbggenerated
     */
    public static final String FD_REMARK = "remark";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.createTime
     *
     * @mbggenerated
     */
    public static final String FD_CREATETIME = "createTime";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.createUser
     *
     * @mbggenerated
     */
    public static final String FD_CREATEUSER = "createUser";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.updateTime
     *
     * @mbggenerated
     */
    public static final String FD_UPDATETIME = "updateTime";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product.updateUser
     *
     * @mbggenerated
     */
    public static final String FD_UPDATEUSER = "updateUser";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.productId
     *
     * @return the value of b_product.productId
     *
     * @mbggenerated
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.productId
     *
     * @param productId the value for b_product.productId
     *
     * @mbggenerated
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.productName
     *
     * @return the value of b_product.productName
     *
     * @mbggenerated
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.productName
     *
     * @param productName the value for b_product.productName
     *
     * @mbggenerated
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.productTypeId
     *
     * @return the value of b_product.productTypeId
     *
     * @mbggenerated
     */
    public Integer getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.productTypeId
     *
     * @param productTypeId the value for b_product.productTypeId
     *
     * @mbggenerated
     */
    public void setProductTypeId(Integer productTypeId) {
        this.productTypeId = productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.saleMoney
     *
     * @return the value of b_product.saleMoney
     *
     * @mbggenerated
     */
    public BigDecimal getSaleMoney() {
        return saleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.saleMoney
     *
     * @param saleMoney the value for b_product.saleMoney
     *
     * @mbggenerated
     */
    public void setSaleMoney(BigDecimal saleMoney) {
        this.saleMoney = saleMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.saleQuantity
     *
     * @return the value of b_product.saleQuantity
     *
     * @mbggenerated
     */
    public Integer getSaleQuantity() {
        return saleQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.saleQuantity
     *
     * @param saleQuantity the value for b_product.saleQuantity
     *
     * @mbggenerated
     */
    public void setSaleQuantity(Integer saleQuantity) {
        this.saleQuantity = saleQuantity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.saleVolumes
     *
     * @return the value of b_product.saleVolumes
     *
     * @mbggenerated
     */
    public Integer getSaleVolumes() {
        return saleVolumes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.saleVolumes
     *
     * @param saleVolumes the value for b_product.saleVolumes
     *
     * @mbggenerated
     */
    public void setSaleVolumes(Integer saleVolumes) {
        this.saleVolumes = saleVolumes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.rebateMoney
     *
     * @return the value of b_product.rebateMoney
     *
     * @mbggenerated
     */
    public BigDecimal getRebateMoney() {
        return rebateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.rebateMoney
     *
     * @param rebateMoney the value for b_product.rebateMoney
     *
     * @mbggenerated
     */
    public void setRebateMoney(BigDecimal rebateMoney) {
        this.rebateMoney = rebateMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.rebatePeriods
     *
     * @return the value of b_product.rebatePeriods
     *
     * @mbggenerated
     */
    public Integer getRebatePeriods() {
        return rebatePeriods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.rebatePeriods
     *
     * @param rebatePeriods the value for b_product.rebatePeriods
     *
     * @mbggenerated
     */
    public void setRebatePeriods(Integer rebatePeriods) {
        this.rebatePeriods = rebatePeriods;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.rebateTotals
     *
     * @return the value of b_product.rebateTotals
     *
     * @mbggenerated
     */
    public BigDecimal getRebateTotals() {
        return rebateTotals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.rebateTotals
     *
     * @param rebateTotals the value for b_product.rebateTotals
     *
     * @mbggenerated
     */
    public void setRebateTotals(BigDecimal rebateTotals) {
        this.rebateTotals = rebateTotals;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.purchaseRestriction
     *
     * @return the value of b_product.purchaseRestriction
     *
     * @mbggenerated
     */
    public Integer getPurchaseRestriction() {
        return purchaseRestriction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.purchaseRestriction
     *
     * @param purchaseRestriction the value for b_product.purchaseRestriction
     *
     * @mbggenerated
     */
    public void setPurchaseRestriction(Integer purchaseRestriction) {
        this.purchaseRestriction = purchaseRestriction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.startRebateTime
     *
     * @return the value of b_product.startRebateTime
     *
     * @mbggenerated
     */
    public Integer getStartRebateTime() {
        return startRebateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.startRebateTime
     *
     * @param startRebateTime the value for b_product.startRebateTime
     *
     * @mbggenerated
     */
    public void setStartRebateTime(Integer startRebateTime) {
        this.startRebateTime = startRebateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.status
     *
     * @return the value of b_product.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.status
     *
     * @param status the value for b_product.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.productImgurl
     *
     * @return the value of b_product.productImgurl
     *
     * @mbggenerated
     */
    public String getProductImgurl() {
        return productImgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.productImgurl
     *
     * @param productImgurl the value for b_product.productImgurl
     *
     * @mbggenerated
     */
    public void setProductImgurl(String productImgurl) {
        this.productImgurl = productImgurl == null ? null : productImgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.sort
     *
     * @return the value of b_product.sort
     *
     * @mbggenerated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.sort
     *
     * @param sort the value for b_product.sort
     *
     * @mbggenerated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.remark
     *
     * @return the value of b_product.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.remark
     *
     * @param remark the value for b_product.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.createTime
     *
     * @return the value of b_product.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.createTime
     *
     * @param createTime the value for b_product.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.createUser
     *
     * @return the value of b_product.createUser
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.createUser
     *
     * @param createUser the value for b_product.createUser
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.updateTime
     *
     * @return the value of b_product.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.updateTime
     *
     * @param updateTime the value for b_product.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product.updateUser
     *
     * @return the value of b_product.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product.updateUser
     *
     * @param updateUser the value for b_product.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productId=").append(productId);
        sb.append(", productName=").append(productName);
        sb.append(", productTypeId=").append(productTypeId);
        sb.append(", saleMoney=").append(saleMoney);
        sb.append(", saleQuantity=").append(saleQuantity);
        sb.append(", saleVolumes=").append(saleVolumes);
        sb.append(", rebateMoney=").append(rebateMoney);
        sb.append(", rebatePeriods=").append(rebatePeriods);
        sb.append(", rebateTotals=").append(rebateTotals);
        sb.append(", purchaseRestriction=").append(purchaseRestriction);
        sb.append(", startRebateTime=").append(startRebateTime);
        sb.append(", status=").append(status);
        sb.append(", productImgurl=").append(productImgurl);
        sb.append(", sort=").append(sort);
        sb.append(", remark=").append(remark);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append(", FD_PRODUCTID=").append(FD_PRODUCTID);
        sb.append(", FD_PRODUCTNAME=").append(FD_PRODUCTNAME);
        sb.append(", FD_PRODUCTTYPEID=").append(FD_PRODUCTTYPEID);
        sb.append(", FD_SALEMONEY=").append(FD_SALEMONEY);
        sb.append(", FD_SALEQUANTITY=").append(FD_SALEQUANTITY);
        sb.append(", FD_SALEVOLUMES=").append(FD_SALEVOLUMES);
        sb.append(", FD_REBATEMONEY=").append(FD_REBATEMONEY);
        sb.append(", FD_REBATEPERIODS=").append(FD_REBATEPERIODS);
        sb.append(", FD_REBATETOTALS=").append(FD_REBATETOTALS);
        sb.append(", FD_PURCHASERESTRICTION=").append(FD_PURCHASERESTRICTION);
        sb.append(", FD_STARTREBATETIME=").append(FD_STARTREBATETIME);
        sb.append(", FD_STATUS=").append(FD_STATUS);
        sb.append(", FD_PRODUCTIMGURL=").append(FD_PRODUCTIMGURL);
        sb.append(", FD_SORT=").append(FD_SORT);
        sb.append(", FD_REMARK=").append(FD_REMARK);
        sb.append(", FD_CREATETIME=").append(FD_CREATETIME);
        sb.append(", FD_CREATEUSER=").append(FD_CREATEUSER);
        sb.append(", FD_UPDATETIME=").append(FD_UPDATETIME);
        sb.append(", FD_UPDATEUSER=").append(FD_UPDATEUSER);
        sb.append("]");
        return sb.toString();
    }
}