package io.frame.dao.entity;

import io.frame.dao.base.BaseEntity;
import java.io.Serializable;
import java.util.Date;

public class ProductType extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.productTypeId
     *
     * @mbggenerated
     */
    private Long productTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.productTypeName
     *
     * @mbggenerated
     */
    private String productTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.createUser
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.updateUser
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_product_type
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.productTypeId
     *
     * @mbggenerated
     */
    public static final String FD_PRODUCTTYPEID = "productTypeId";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.productTypeName
     *
     * @mbggenerated
     */
    public static final String FD_PRODUCTTYPENAME = "productTypeName";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.status
     *
     * @mbggenerated
     */
    public static final String FD_STATUS = "status";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.createTime
     *
     * @mbggenerated
     */
    public static final String FD_CREATETIME = "createTime";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.createUser
     *
     * @mbggenerated
     */
    public static final String FD_CREATEUSER = "createUser";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.updateTime
     *
     * @mbggenerated
     */
    public static final String FD_UPDATETIME = "updateTime";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_product_type.updateUser
     *
     * @mbggenerated
     */
    public static final String FD_UPDATEUSER = "updateUser";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_type.productTypeId
     *
     * @return the value of b_product_type.productTypeId
     *
     * @mbggenerated
     */
    public Long getProductTypeId() {
        return productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_type.productTypeId
     *
     * @param productTypeId the value for b_product_type.productTypeId
     *
     * @mbggenerated
     */
    public void setProductTypeId(Long productTypeId) {
        this.productTypeId = productTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_type.productTypeName
     *
     * @return the value of b_product_type.productTypeName
     *
     * @mbggenerated
     */
    public String getProductTypeName() {
        return productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_type.productTypeName
     *
     * @param productTypeName the value for b_product_type.productTypeName
     *
     * @mbggenerated
     */
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName == null ? null : productTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_type.status
     *
     * @return the value of b_product_type.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_type.status
     *
     * @param status the value for b_product_type.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_type.createTime
     *
     * @return the value of b_product_type.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_type.createTime
     *
     * @param createTime the value for b_product_type.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_type.createUser
     *
     * @return the value of b_product_type.createUser
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_type.createUser
     *
     * @param createUser the value for b_product_type.createUser
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_type.updateTime
     *
     * @return the value of b_product_type.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_type.updateTime
     *
     * @param updateTime the value for b_product_type.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_product_type.updateUser
     *
     * @return the value of b_product_type.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_product_type.updateUser
     *
     * @param updateUser the value for b_product_type.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_product_type
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", productTypeId=").append(productTypeId);
        sb.append(", productTypeName=").append(productTypeName);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append(", FD_PRODUCTTYPEID=").append(FD_PRODUCTTYPEID);
        sb.append(", FD_PRODUCTTYPENAME=").append(FD_PRODUCTTYPENAME);
        sb.append(", FD_STATUS=").append(FD_STATUS);
        sb.append(", FD_CREATETIME=").append(FD_CREATETIME);
        sb.append(", FD_CREATEUSER=").append(FD_CREATEUSER);
        sb.append(", FD_UPDATETIME=").append(FD_UPDATETIME);
        sb.append(", FD_UPDATEUSER=").append(FD_UPDATEUSER);
        sb.append("]");
        return sb.toString();
    }
}