package io.frame.dao.entity;

import io.frame.dao.base.BaseEntity;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Recommend extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.recommendId
     *
     * @mbggenerated
     */
    private Long recommendId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.userId
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.userName
     *
     * @mbggenerated
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.parentId
     *
     * @mbggenerated
     */
    private Long parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.groupUserIds
     *
     * @mbggenerated
     */
    private String groupUserIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.recommendNumber
     *
     * @mbggenerated
     */
    private Integer recommendNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.teamAchievement
     *
     * @mbggenerated
     */
    private BigDecimal teamAchievement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.createUser
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.updateUser
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.recommendId
     *
     * @mbggenerated
     */
    public static final String FD_RECOMMENDID = "recommendId";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.userId
     *
     * @mbggenerated
     */
    public static final String FD_USERID = "userId";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.userName
     *
     * @mbggenerated
     */
    public static final String FD_USERNAME = "userName";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.parentId
     *
     * @mbggenerated
     */
    public static final String FD_PARENTID = "parentId";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.groupUserIds
     *
     * @mbggenerated
     */
    public static final String FD_GROUPUSERIDS = "groupUserIds";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.recommendNumber
     *
     * @mbggenerated
     */
    public static final String FD_RECOMMENDNUMBER = "recommendNumber";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.teamAchievement
     *
     * @mbggenerated
     */
    public static final String FD_TEAMACHIEVEMENT = "teamAchievement";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.createTime
     *
     * @mbggenerated
     */
    public static final String FD_CREATETIME = "createTime";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.createUser
     *
     * @mbggenerated
     */
    public static final String FD_CREATEUSER = "createUser";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.updateTime
     *
     * @mbggenerated
     */
    public static final String FD_UPDATETIME = "updateTime";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_recommend.updateUser
     *
     * @mbggenerated
     */
    public static final String FD_UPDATEUSER = "updateUser";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_recommend.recommendId
     *
     * @return the value of u_recommend.recommendId
     *
     * @mbggenerated
     */
    public Long getRecommendId() {
        return recommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_recommend.recommendId
     *
     * @param recommendId the value for u_recommend.recommendId
     *
     * @mbggenerated
     */
    public void setRecommendId(Long recommendId) {
        this.recommendId = recommendId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_recommend.userId
     *
     * @return the value of u_recommend.userId
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_recommend.userId
     *
     * @param userId the value for u_recommend.userId
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_recommend.userName
     *
     * @return the value of u_recommend.userName
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_recommend.userName
     *
     * @param userName the value for u_recommend.userName
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_recommend.parentId
     *
     * @return the value of u_recommend.parentId
     *
     * @mbggenerated
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_recommend.parentId
     *
     * @param parentId the value for u_recommend.parentId
     *
     * @mbggenerated
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_recommend.groupUserIds
     *
     * @return the value of u_recommend.groupUserIds
     *
     * @mbggenerated
     */
    public String getGroupUserIds() {
        return groupUserIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_recommend.groupUserIds
     *
     * @param groupUserIds the value for u_recommend.groupUserIds
     *
     * @mbggenerated
     */
    public void setGroupUserIds(String groupUserIds) {
        this.groupUserIds = groupUserIds == null ? null : groupUserIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_recommend.recommendNumber
     *
     * @return the value of u_recommend.recommendNumber
     *
     * @mbggenerated
     */
    public Integer getRecommendNumber() {
        return recommendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_recommend.recommendNumber
     *
     * @param recommendNumber the value for u_recommend.recommendNumber
     *
     * @mbggenerated
     */
    public void setRecommendNumber(Integer recommendNumber) {
        this.recommendNumber = recommendNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_recommend.teamAchievement
     *
     * @return the value of u_recommend.teamAchievement
     *
     * @mbggenerated
     */
    public BigDecimal getTeamAchievement() {
        return teamAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_recommend.teamAchievement
     *
     * @param teamAchievement the value for u_recommend.teamAchievement
     *
     * @mbggenerated
     */
    public void setTeamAchievement(BigDecimal teamAchievement) {
        this.teamAchievement = teamAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_recommend.createTime
     *
     * @return the value of u_recommend.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_recommend.createTime
     *
     * @param createTime the value for u_recommend.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_recommend.createUser
     *
     * @return the value of u_recommend.createUser
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_recommend.createUser
     *
     * @param createUser the value for u_recommend.createUser
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_recommend.updateTime
     *
     * @return the value of u_recommend.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_recommend.updateTime
     *
     * @param updateTime the value for u_recommend.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_recommend.updateUser
     *
     * @return the value of u_recommend.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_recommend.updateUser
     *
     * @param updateUser the value for u_recommend.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_recommend
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recommendId=").append(recommendId);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", parentId=").append(parentId);
        sb.append(", groupUserIds=").append(groupUserIds);
        sb.append(", recommendNumber=").append(recommendNumber);
        sb.append(", teamAchievement=").append(teamAchievement);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append(", FD_RECOMMENDID=").append(FD_RECOMMENDID);
        sb.append(", FD_USERID=").append(FD_USERID);
        sb.append(", FD_USERNAME=").append(FD_USERNAME);
        sb.append(", FD_PARENTID=").append(FD_PARENTID);
        sb.append(", FD_GROUPUSERIDS=").append(FD_GROUPUSERIDS);
        sb.append(", FD_RECOMMENDNUMBER=").append(FD_RECOMMENDNUMBER);
        sb.append(", FD_TEAMACHIEVEMENT=").append(FD_TEAMACHIEVEMENT);
        sb.append(", FD_CREATETIME=").append(FD_CREATETIME);
        sb.append(", FD_CREATEUSER=").append(FD_CREATEUSER);
        sb.append(", FD_UPDATETIME=").append(FD_UPDATETIME);
        sb.append(", FD_UPDATEUSER=").append(FD_UPDATEUSER);
        sb.append("]");
        return sb.toString();
    }
}