package io.frame.dao.entity;

import io.frame.dao.base.BaseEntity;
import java.io.Serializable;

public class SysRoleMenu extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_sys_role_menu.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_sys_role_menu.roleId
     *
     * @mbggenerated
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_sys_role_menu.menuId
     *
     * @mbggenerated
     */
    private Long menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s_sys_role_menu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_sys_role_menu.id
     *
     * @mbggenerated
     */
    public static final String FD_ID = "id";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_sys_role_menu.roleId
     *
     * @mbggenerated
     */
    public static final String FD_ROLEID = "roleId";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s_sys_role_menu.menuId
     *
     * @mbggenerated
     */
    public static final String FD_MENUID = "menuId";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_sys_role_menu.id
     *
     * @return the value of s_sys_role_menu.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_sys_role_menu.id
     *
     * @param id the value for s_sys_role_menu.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_sys_role_menu.roleId
     *
     * @return the value of s_sys_role_menu.roleId
     *
     * @mbggenerated
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_sys_role_menu.roleId
     *
     * @param roleId the value for s_sys_role_menu.roleId
     *
     * @mbggenerated
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s_sys_role_menu.menuId
     *
     * @return the value of s_sys_role_menu.menuId
     *
     * @mbggenerated
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s_sys_role_menu.menuId
     *
     * @param menuId the value for s_sys_role_menu.menuId
     *
     * @mbggenerated
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s_sys_role_menu
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", menuId=").append(menuId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append(", FD_ID=").append(FD_ID);
        sb.append(", FD_ROLEID=").append(FD_ROLEID);
        sb.append(", FD_MENUID=").append(FD_MENUID);
        sb.append("]");
        return sb.toString();
    }
}