package io.frame.dao.entity;

import io.frame.dao.base.BaseEntity;
import java.io.Serializable;
import java.util.Date;

public class Token extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_token.userId
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_token.token
     *
     * @mbggenerated
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_token.expireTime
     *
     * @mbggenerated
     */
    private Date expireTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_token.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_token
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_token.userId
     *
     * @mbggenerated
     */
    public static final String FD_USERID = "userId";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_token.token
     *
     * @mbggenerated
     */
    public static final String FD_TOKEN = "token";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_token.expireTime
     *
     * @mbggenerated
     */
    public static final String FD_EXPIRETIME = "expireTime";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_token.updateTime
     *
     * @mbggenerated
     */
    public static final String FD_UPDATETIME = "updateTime";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_token.userId
     *
     * @return the value of u_token.userId
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_token.userId
     *
     * @param userId the value for u_token.userId
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_token.token
     *
     * @return the value of u_token.token
     *
     * @mbggenerated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_token.token
     *
     * @param token the value for u_token.token
     *
     * @mbggenerated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_token.expireTime
     *
     * @return the value of u_token.expireTime
     *
     * @mbggenerated
     */
    public Date getExpireTime() {
        return expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_token.expireTime
     *
     * @param expireTime the value for u_token.expireTime
     *
     * @mbggenerated
     */
    public void setExpireTime(Date expireTime) {
        this.expireTime = expireTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_token.updateTime
     *
     * @return the value of u_token.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_token.updateTime
     *
     * @param updateTime the value for u_token.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_token
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userId=").append(userId);
        sb.append(", token=").append(token);
        sb.append(", expireTime=").append(expireTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append(", FD_USERID=").append(FD_USERID);
        sb.append(", FD_TOKEN=").append(FD_TOKEN);
        sb.append(", FD_EXPIRETIME=").append(FD_EXPIRETIME);
        sb.append(", FD_UPDATETIME=").append(FD_UPDATETIME);
        sb.append("]");
        return sb.toString();
    }
}