package io.frame.dao.entity;

import io.frame.dao.base.BaseEntity;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Wallet extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.walletId
     *
     * @mbggenerated
     */
    private Long walletId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.userId
     *
     * @mbggenerated
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.balance
     *
     * @mbggenerated
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.profitMoney
     *
     * @mbggenerated
     */
    private BigDecimal profitMoney;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.createTime
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.createUser
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.updateTime
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.updateUser
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table u_wallet
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.walletId
     *
     * @mbggenerated
     */
    public static final String FD_WALLETID = "walletId";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.userId
     *
     * @mbggenerated
     */
    public static final String FD_USERID = "userId";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.balance
     *
     * @mbggenerated
     */
    public static final String FD_BALANCE = "balance";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.profitMoney
     *
     * @mbggenerated
     */
    public static final String FD_PROFITMONEY = "profitMoney";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.createTime
     *
     * @mbggenerated
     */
    public static final String FD_CREATETIME = "createTime";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.createUser
     *
     * @mbggenerated
     */
    public static final String FD_CREATEUSER = "createUser";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.updateTime
     *
     * @mbggenerated
     */
    public static final String FD_UPDATETIME = "updateTime";

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column u_wallet.updateUser
     *
     * @mbggenerated
     */
    public static final String FD_UPDATEUSER = "updateUser";

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_wallet.walletId
     *
     * @return the value of u_wallet.walletId
     *
     * @mbggenerated
     */
    public Long getWalletId() {
        return walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_wallet.walletId
     *
     * @param walletId the value for u_wallet.walletId
     *
     * @mbggenerated
     */
    public void setWalletId(Long walletId) {
        this.walletId = walletId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_wallet.userId
     *
     * @return the value of u_wallet.userId
     *
     * @mbggenerated
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_wallet.userId
     *
     * @param userId the value for u_wallet.userId
     *
     * @mbggenerated
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_wallet.balance
     *
     * @return the value of u_wallet.balance
     *
     * @mbggenerated
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_wallet.balance
     *
     * @param balance the value for u_wallet.balance
     *
     * @mbggenerated
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_wallet.profitMoney
     *
     * @return the value of u_wallet.profitMoney
     *
     * @mbggenerated
     */
    public BigDecimal getProfitMoney() {
        return profitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_wallet.profitMoney
     *
     * @param profitMoney the value for u_wallet.profitMoney
     *
     * @mbggenerated
     */
    public void setProfitMoney(BigDecimal profitMoney) {
        this.profitMoney = profitMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_wallet.createTime
     *
     * @return the value of u_wallet.createTime
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_wallet.createTime
     *
     * @param createTime the value for u_wallet.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_wallet.createUser
     *
     * @return the value of u_wallet.createUser
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_wallet.createUser
     *
     * @param createUser the value for u_wallet.createUser
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser == null ? null : createUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_wallet.updateTime
     *
     * @return the value of u_wallet.updateTime
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_wallet.updateTime
     *
     * @param updateTime the value for u_wallet.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column u_wallet.updateUser
     *
     * @return the value of u_wallet.updateUser
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column u_wallet.updateUser
     *
     * @param updateUser the value for u_wallet.updateUser
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser == null ? null : updateUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table u_wallet
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", walletId=").append(walletId);
        sb.append(", userId=").append(userId);
        sb.append(", balance=").append(balance);
        sb.append(", profitMoney=").append(profitMoney);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append(", FD_WALLETID=").append(FD_WALLETID);
        sb.append(", FD_USERID=").append(FD_USERID);
        sb.append(", FD_BALANCE=").append(FD_BALANCE);
        sb.append(", FD_PROFITMONEY=").append(FD_PROFITMONEY);
        sb.append(", FD_CREATETIME=").append(FD_CREATETIME);
        sb.append(", FD_CREATEUSER=").append(FD_CREATEUSER);
        sb.append(", FD_UPDATETIME=").append(FD_UPDATETIME);
        sb.append(", FD_UPDATEUSER=").append(FD_UPDATEUSER);
        sb.append("]");
        return sb.toString();
    }
}