package io.frame.dao.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WelfareExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public WelfareExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public void setOrderByClauseIgnoreNull(String orderByClause) {
        String tmp = orderByClause.toLowerCase().replace("null", "").replace("asc", "").replace("desc", "").trim();
        if (orderByClause != null && tmp.length() > 0) {
            this.orderByClause = orderByClause;}
        }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWelfareIdIsNull() {
            addCriterion("welfareId is null");
            return (Criteria) this;
        }

        public Criteria andWelfareIdIsNotNull() {
            addCriterion("welfareId is not null");
            return (Criteria) this;
        }

        public Criteria andWelfareIdEqualTo(Long value) {
            addCriterion("welfareId =", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdNotEqualTo(Long value) {
            addCriterion("welfareId <>", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdGreaterThan(Long value) {
            addCriterion("welfareId >", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdGreaterThanOrEqualTo(Long value) {
            addCriterion("welfareId >=", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdLessThan(Long value) {
            addCriterion("welfareId <", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdLessThanOrEqualTo(Long value) {
            addCriterion("welfareId <=", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdIn(List<Long> values) {
            addCriterion("welfareId in", values, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdNotIn(List<Long> values) {
            addCriterion("welfareId not in", values, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdBetween(Long value1, Long value2) {
            addCriterion("welfareId between", value1, value2, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdNotBetween(Long value1, Long value2) {
            addCriterion("welfareId not between", value1, value2, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyIsNull() {
            addCriterion("welfareKey is null");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyIsNotNull() {
            addCriterion("welfareKey is not null");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyEqualTo(String value) {
            addCriterion("welfareKey =", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyNotEqualTo(String value) {
            addCriterion("welfareKey <>", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyGreaterThan(String value) {
            addCriterion("welfareKey >", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyGreaterThanOrEqualTo(String value) {
            addCriterion("welfareKey >=", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyLessThan(String value) {
            addCriterion("welfareKey <", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyLessThanOrEqualTo(String value) {
            addCriterion("welfareKey <=", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyLike(String value) {
            addCriterion("welfareKey like", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyNotLike(String value) {
            addCriterion("welfareKey not like", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyIn(List<String> values) {
            addCriterion("welfareKey in", values, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyNotIn(List<String> values) {
            addCriterion("welfareKey not in", values, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyBetween(String value1, String value2) {
            addCriterion("welfareKey between", value1, value2, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyNotBetween(String value1, String value2) {
            addCriterion("welfareKey not between", value1, value2, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareNameIsNull() {
            addCriterion("welfareName is null");
            return (Criteria) this;
        }

        public Criteria andWelfareNameIsNotNull() {
            addCriterion("welfareName is not null");
            return (Criteria) this;
        }

        public Criteria andWelfareNameEqualTo(String value) {
            addCriterion("welfareName =", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameNotEqualTo(String value) {
            addCriterion("welfareName <>", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameGreaterThan(String value) {
            addCriterion("welfareName >", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameGreaterThanOrEqualTo(String value) {
            addCriterion("welfareName >=", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameLessThan(String value) {
            addCriterion("welfareName <", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameLessThanOrEqualTo(String value) {
            addCriterion("welfareName <=", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameLike(String value) {
            addCriterion("welfareName like", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameNotLike(String value) {
            addCriterion("welfareName not like", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameIn(List<String> values) {
            addCriterion("welfareName in", values, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameNotIn(List<String> values) {
            addCriterion("welfareName not in", values, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameBetween(String value1, String value2) {
            addCriterion("welfareName between", value1, value2, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameNotBetween(String value1, String value2) {
            addCriterion("welfareName not between", value1, value2, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareValueIsNull() {
            addCriterion("welfareValue is null");
            return (Criteria) this;
        }

        public Criteria andWelfareValueIsNotNull() {
            addCriterion("welfareValue is not null");
            return (Criteria) this;
        }

        public Criteria andWelfareValueEqualTo(String value) {
            addCriterion("welfareValue =", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueNotEqualTo(String value) {
            addCriterion("welfareValue <>", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueGreaterThan(String value) {
            addCriterion("welfareValue >", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueGreaterThanOrEqualTo(String value) {
            addCriterion("welfareValue >=", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueLessThan(String value) {
            addCriterion("welfareValue <", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueLessThanOrEqualTo(String value) {
            addCriterion("welfareValue <=", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueLike(String value) {
            addCriterion("welfareValue like", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueNotLike(String value) {
            addCriterion("welfareValue not like", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueIn(List<String> values) {
            addCriterion("welfareValue in", values, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueNotIn(List<String> values) {
            addCriterion("welfareValue not in", values, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueBetween(String value1, String value2) {
            addCriterion("welfareValue between", value1, value2, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueNotBetween(String value1, String value2) {
            addCriterion("welfareValue not between", value1, value2, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andBonusPoolIsNull() {
            addCriterion("bonusPool is null");
            return (Criteria) this;
        }

        public Criteria andBonusPoolIsNotNull() {
            addCriterion("bonusPool is not null");
            return (Criteria) this;
        }

        public Criteria andBonusPoolEqualTo(BigDecimal value) {
            addCriterion("bonusPool =", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolNotEqualTo(BigDecimal value) {
            addCriterion("bonusPool <>", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolGreaterThan(BigDecimal value) {
            addCriterion("bonusPool >", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bonusPool >=", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolLessThan(BigDecimal value) {
            addCriterion("bonusPool <", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bonusPool <=", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolIn(List<BigDecimal> values) {
            addCriterion("bonusPool in", values, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolNotIn(List<BigDecimal> values) {
            addCriterion("bonusPool not in", values, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bonusPool between", value1, value2, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bonusPool not between", value1, value2, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("createTime is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("createTime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("createTime in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("createTime not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("createTime between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("createTime not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("createUser is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("createUser is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("createUser =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("createUser <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("createUser >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("createUser >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("createUser <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("createUser <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("createUser like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("createUser not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("createUser in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("createUser not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("createUser between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("createUser not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("updateTime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("updateTime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("updateTime =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("updateTime <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("updateTime >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updateTime >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("updateTime <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("updateTime <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("updateTime in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("updateTime not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("updateTime between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("updateTime not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("updateUser is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("updateUser is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("updateUser =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("updateUser <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("updateUser >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("updateUser >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("updateUser <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("updateUser <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("updateUser like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("updateUser not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("updateUser in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("updateUser not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("updateUser between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("updateUser not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyLikeInsensitive(String value) {
            addCriterion("upper(welfareKey) like", value.toUpperCase(), "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareNameLikeInsensitive(String value) {
            addCriterion("upper(welfareName) like", value.toUpperCase(), "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareValueLikeInsensitive(String value) {
            addCriterion("upper(welfareValue) like", value.toUpperCase(), "welfareValue");
            return (Criteria) this;
        }

        public Criteria andCreateUserLikeInsensitive(String value) {
            addCriterion("upper(createUser) like", value.toUpperCase(), "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLikeInsensitive(String value) {
            addCriterion("upper(updateUser) like", value.toUpperCase(), "updateUser");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }

        protected void addCriterionIgnoreNull(String condition, Object value, String property) {
            if (value != null) {
                if (value instanceof String) {
                    if (condition.toLowerCase().endsWith("like")) {
                        if (((String) value).replaceAll("%", "").length() > 0) {
                            criteria.add(new Criterion(condition, value));
                        }
                    } else if (((String) value).length() > 0) {
                        criteria.add(new Criterion(condition, value));
                    }
                } else if (value instanceof List<?>) {
                    if (((List<?>) value).size() > 0) {
                        criteria.add(new Criterion(condition, value));
                    }
                } else {
                    criteria.add(new Criterion(condition, value));
                }
            }
        }

        public Criteria andWelfareIdEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("welfareId =", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdNotEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("welfareId <>", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdGreaterThanIgnoreNull(Long value) {
            addCriterionIgnoreNull("welfareId >", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdGreaterThanOrEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("welfareId >=", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdLessThanIgnoreNull(Long value) {
            addCriterionIgnoreNull("welfareId <", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdLessThanOrEqualToIgnoreNull(Long value) {
            addCriterionIgnoreNull("welfareId <=", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdInIgnoreNull(List<Long> value) {
            addCriterionIgnoreNull("welfareId in", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareIdNotInIgnoreNull(List<Long> value) {
            addCriterionIgnoreNull("welfareId not in", value, "welfareId");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareKey =", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareKey <>", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareKey >", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareKey >=", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareKey <", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareKey <=", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareKey like", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareKey not like", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("welfareKey in", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("welfareKey not in", value, "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareNameEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareName =", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareName <>", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareName >", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareName >=", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareName <", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareName <=", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareName like", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareName not like", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("welfareName in", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareNameNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("welfareName not in", value, "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareValueEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareValue =", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareValue <>", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareValue >", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareValue >=", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareValue <", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareValue <=", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareValue like", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("welfareValue not like", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("welfareValue in", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andWelfareValueNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("welfareValue not in", value, "welfareValue");
            return (Criteria) this;
        }

        public Criteria andBonusPoolEqualToIgnoreNull(BigDecimal value) {
            addCriterionIgnoreNull("bonusPool =", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolNotEqualToIgnoreNull(BigDecimal value) {
            addCriterionIgnoreNull("bonusPool <>", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolGreaterThanIgnoreNull(BigDecimal value) {
            addCriterionIgnoreNull("bonusPool >", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolGreaterThanOrEqualToIgnoreNull(BigDecimal value) {
            addCriterionIgnoreNull("bonusPool >=", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolLessThanIgnoreNull(BigDecimal value) {
            addCriterionIgnoreNull("bonusPool <", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolLessThanOrEqualToIgnoreNull(BigDecimal value) {
            addCriterionIgnoreNull("bonusPool <=", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolInIgnoreNull(List<BigDecimal> value) {
            addCriterionIgnoreNull("bonusPool in", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andBonusPoolNotInIgnoreNull(List<BigDecimal> value) {
            addCriterionIgnoreNull("bonusPool not in", value, "bonusPool");
            return (Criteria) this;
        }

        public Criteria andStatusEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanIgnoreNull(Integer value) {
            addCriterionIgnoreNull("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualToIgnoreNull(Integer value) {
            addCriterionIgnoreNull("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("status in", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotInIgnoreNull(List<Integer> value) {
            addCriterionIgnoreNull("status not in", value, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("createTime <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("createTime in", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("createTime not in", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("createUser not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("createUser in", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("createUser not in", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("updateTime =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("updateTime <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("updateTime >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("updateTime >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanIgnoreNull(Date value) {
            addCriterionIgnoreNull("updateTime <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualToIgnoreNull(Date value) {
            addCriterionIgnoreNull("updateTime <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("updateTime in", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotInIgnoreNull(List<Date> value) {
            addCriterionIgnoreNull("updateTime not in", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("updateUser not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("updateUser in", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("updateUser not in", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanIgnoreNull(String value) {
            addCriterionIgnoreNull("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanIgnoreNull(String value) {
            addCriterionIgnoreNull("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualToIgnoreNull(String value) {
            addCriterionIgnoreNull("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLikeIgnoreNull(String value) {
            addCriterionIgnoreNull("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("remark in", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotInIgnoreNull(List<String> value) {
            addCriterionIgnoreNull("remark not in", value, "remark");
            return (Criteria) this;
        }

        public Criteria andWelfareKeyLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(welfareKey) like", value.toUpperCase(), "welfareKey");
            return (Criteria) this;
        }

        public Criteria andWelfareNameLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(welfareName) like", value.toUpperCase(), "welfareName");
            return (Criteria) this;
        }

        public Criteria andWelfareValueLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(welfareValue) like", value.toUpperCase(), "welfareValue");
            return (Criteria) this;
        }

        public Criteria andCreateUserLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(createUser) like", value.toUpperCase(), "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(updateUser) like", value.toUpperCase(), "updateUser");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitiveIgnoreNull(String value) {
            addCriterionIgnoreNull("upper(remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }

        public Criteria andWelfareIdLikeInsensitive(String value) {
            addCriterion("upper(welfareId) like", value.toUpperCase(), "welfareId");
            return this;
        }

        public Criteria andWelfareKeyLikeInsensitive(String value) {
            addCriterion("upper(welfareKey) like", value.toUpperCase(), "welfareKey");
            return this;
        }

        public Criteria andWelfareNameLikeInsensitive(String value) {
            addCriterion("upper(welfareName) like", value.toUpperCase(), "welfareName");
            return this;
        }

        public Criteria andWelfareValueLikeInsensitive(String value) {
            addCriterion("upper(welfareValue) like", value.toUpperCase(), "welfareValue");
            return this;
        }

        public Criteria andBonusPoolLikeInsensitive(String value) {
            addCriterion("upper(bonusPool) like", value.toUpperCase(), "bonusPool");
            return this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(status) like", value.toUpperCase(), "status");
            return this;
        }

        public Criteria andCreateTimeLikeInsensitive(String value) {
            addCriterion("upper(createTime) like", value.toUpperCase(), "createTime");
            return this;
        }

        public Criteria andCreateUserLikeInsensitive(String value) {
            addCriterion("upper(createUser) like", value.toUpperCase(), "createUser");
            return this;
        }

        public Criteria andUpdateTimeLikeInsensitive(String value) {
            addCriterion("upper(updateTime) like", value.toUpperCase(), "updateTime");
            return this;
        }

        public Criteria andUpdateUserLikeInsensitive(String value) {
            addCriterion("upper(updateUser) like", value.toUpperCase(), "updateUser");
            return this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_welfare
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}